### ISSUE TITLE
关于结构体数组的嵌套

### ISSUE THREAD

**Issue by xd5520026** [armink/struct2json#1]
目前struct2json的json数组只支持int、string、double等基本类型。但不支持数组嵌套json类，所以不能对嵌套了“结构体数组”的结构体进行转换。能否考虑增加json数组对json类的嵌套，以适用于更加灵活的结构体类型。

**Comment by armink** [comment]
这个功能涉及到嵌套处理，实现起来挺麻烦的。你有没有好的方法呢？

**Comment by calvinwilliams** [comment]
DirectStruct支持固定大小和不固定大小数组嵌套序列化/反序列化。DirectStruct可以生成全部的C结构体变量与JSON报文之间的序列化/反序列化函数代码，应用要做的只是调用一个函数即可。DirectStruct还能生成C结构体变量与XML报文、二进制报文的序列化/反序列化函数代码；还能生成数据库建表脚本和ESQL代码  ；）
