### ISSUE TITLE
create缺少对应的delete方法

### ISSUE THREAD

**Issue by zbcfscc** [armink/struct2json#3]
s2j_create_json_obj和s2j_create_struct_obj接口没有对应的delete方法。

s2j_create_json_obj可以用cJSON_Delete去删除，但是使用上有点混乱，建议增加一个s2j_delete_json_obj.

s2j_create_struct_obj中可以使用自定义的malloc_fn函数，如果没有对应的s2j_delete_struct_obj，那么s2j_init中传入的free_fn就没有起到作用。

示例的main.c文件，退出前没有释放申请的obj，建议增加释放操作。

**Comment by armink** [comment]
感谢反馈，我下周加上。
